<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="InputMapper.fs" />
    <Compile Include="Program.fs" />
    <Compile Include="Runtime.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mibo.MonoGame\Mibo.MonoGame.fsproj" />
    <ProjectReference Include="..\Mibo.Mvu\Mibo.Mvu.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.Native" Version="3.8.5" PrivateAssets="all" />
    <PackageReference Include="Ionide.KeepAChangelog.Tasks" Version="0.3.3" PrivateAssets="all" />
  </ItemGroup>

</Project>
