<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Mibo.Core.Tests" />
    <InternalsVisibleTo Include="Mibo.Raylib" />
    <InternalsVisibleTo Include="Mibo.Raylib.Tests" />
    <InternalsVisibleTo Include="Mibo.MonoGame" />
    <InternalsVisibleTo Include="Mibo.Mvu" />
    <InternalsVisibleTo Include="Mibo.Mvu.Tests" />
    <InternalsVisibleTo Include="Mibo.Adaptive.Mibo" />
    <InternalsVisibleTo Include="Mibo.Adaptive.Mibo.Tests" />
    <InternalsVisibleTo Include="Mibo.Raylib.Mvu" />
    <InternalsVisibleTo Include="Mibo.Raylib.Adaptive" />
    <InternalsVisibleTo Include="Mibo.MonoGame.Mvu" />
    <InternalsVisibleTo Include="Mibo.MonoGame.Adaptive" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Collections.fs" />
    <Compile Include="Color.fs" />
    <Compile Include="Animation3D.fs" />
    <Compile Include="SubId.fs" />
    <Compile Include="Time.fs" />
    <Compile Include="Rendering.fs" />
    <Compile Include="Diagnostics.fs" />
    <Compile Include="Window.fs" />
    <Compile Include="GameConfig.fs" />
    <Compile Include="Assets.fs" />
    <Compile Include="Input.fs" />
    <Compile Include="InputMapper.fs" />
    <Compile Include="InputServices.fs" />
    <Compile Include="Layout/Grid2D.fs" />
    <Compile Include="Layout/HexGrid.fs" />
    <Compile Include="Layout/Spatial2D.fs" />
    <Compile Include="Layout/HexLayout.fs" />
    <Compile Include="Layout/LayeredHex.fs" />
    <Compile Include="Layout/Layout.fs" />
    <Compile Include="Layout/Platformer.fs" />
    <Compile Include="Layout/TopDown.fs" />
    <Compile Include="Layout/Layered.fs" />
    <Compile Include="Layout3D/Grid3D.fs" />
    <Compile Include="Layout3D/HexGrid3D.fs" />
    <Compile Include="Layout3D/Spatial3D.fs" />
    <Compile Include="Layout3D/Layout3D.fs" />
    <Compile Include="Layout3D/HexLayout3D.fs" />
    <Compile Include="Layout3D/LayeredHex3D.fs" />
    <Compile Include="Layout3D/LayeredGrid3D.fs" />
    <Compile Include="Layout3D/Interior.fs" />
    <Compile Include="Layout3D/Terrain.fs" />
    <Compile Include="Graphics3D/Light3D.fs" />
    <Compile Include="Graphics2D/Types.fs" />
    <Compile Include="Graphics/Draw.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.UMX" Version="1.1.0" />
    <PackageReference Include="Ionide.KeepAChangelog.Tasks" Version="0.3.3" PrivateAssets="all" />
  </ItemGroup>

</Project>
