<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="GameContext.fs" />
    <Compile Include="Input.fs" />
    <Compile Include="InputMapper.fs" />
    <Compile Include="Assets.fs" />
    <Compile Include="Runtime.fs" />
    <Compile Include="Graphics2D/Camera2D.fs" />
    <Compile Include="Graphics2D/Command2D.fs" />
    <Compile Include="Graphics2D/RenderBuffer2D.fs" />
    <Compile Include="Graphics2D/Renderer2D.fs" />
    <Compile Include="Graphics2D/Draw.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mibo.Core\Mibo.Core.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.Native" Version="3.8.4.1" />
    <PackageReference Include="FSharp.UMX" Version="1.1.0" />
  </ItemGroup>

</Project>
