<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="InputMapperTests.fs" />
    <Compile Include="ElmishTests.fs" />
    <Compile Include="HeadlessTests.fs" />
    <Compile Include="LayoutTests.fs" />
    <Compile Include="HexGridTests.fs" />
    <Compile Include="HexLayoutTests.fs" />
    <Compile Include="LayeredHexTests.fs" />
    <Compile Include="HexGrid3DTests.fs" />
    <Compile Include="HexLayout3DTests.fs" />
    <Compile Include="LayeredHex3DTests.fs" />
    <Compile Include="Spatial2DTests.fs" />
    <Compile Include="Spatial3DTests.fs" />
    <Compile Include="AdaptiveHeadlessTests.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mibo.Core\Mibo.Core.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IcedTasks" Version="0.11.9" />
    <PackageReference Include="Expecto" Version="10.*" />
    <PackageReference Include="YoloDev.Expecto.TestSdk" Version="0.15.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
  </ItemGroup>
</Project>
